### ISSUE TITLE
`error: 'rbegin' is not a member of 'std'` - C++11 compliancy

### ISSUE THREAD

**Issue by knedlsepp** [ryanhaining/cppitertools#23]
I am experiencing problems compiling with gcc-4.9.3. On trying to compile a simple `zip`, I get the following error message:
> cppitertools/reversed.hpp:29:16: error: 'rbegin' is not a member of 'std'

It seems to me that this issue is due to cppitertools using C++14 features and my standard library not being C++14 compliant, as is explained [here](http://stackoverflow.com/questions/27922141/stdrbegin-and-stdrend-function-in-gcc-4-9-and-clang-3-5).
Should the library still work in a C++11 environment or is there some other problem on my behalf?

**Edit:**
I now tested with gcc-5.3 and `-std=c++11`, which gives similar errors. Activating `-std=c++14` fixes the problem.
The issue boils down to:
> Implementation of python itertools and builtin iteration functions for **C++14**

**Comment by ryanhaining** [comment]
Yes I've been working on the C++14 branch for some time, but enough time has passed (imo) to stop active development on both C++11 and C++14. You are right that [gcc-4.9 with its libstdc++](http://coliru.stacked-crooked.com/a/e0a07cd7df65911a) was missing `std::rbegin` and `std::rend` which are both [new to C++14](http://en.cppreference.com/w/cpp/iterator/rbegin). They are supported as of the gcc-5 series.

If you can't use a library with the newer C++14 functions, you can comment out the code that uses it, or remove `#include <reveresed.hpp>` from `itertools.hpp`. As far as I recall `reversed` is the only one that uses them. Otherwise stick with [v0.1](https://github.com/ryanhaining/cppitertools/releases/tag/v0.1) which is a less than ideal fix.

**Comment by knedlsepp** [comment]
Ok. Thanks for the info.
