### ISSUE TITLE
count not working for negative non-integer step

### ISSUE THREAD

**Issue by pedrogarciafreitas** [ryanhaining/cppitertools#60]
The following statements do not work:

```cpp
const std::vector<double> expected{1.0, 0.5, 0.0, -0.5, -1.0};
  std::vector<double> counted;
  for (auto c : count(1.0, -0.5)) {
    counted.push_back(c);
    if (c <= -1.0) break;
  }
  for (int i : range(expected.size()))
    EXPECT_DOUBLE_EQ(expected[i], counted[i]);
```

Output errors:

`
Expected equality of these values:
  expected[i]
    Which is: 0
  counted[i]
    Which is: 2.1219957913605248e-313
/home/pedrogf/Projects/LightFields/ReferenceSoftware/REPO/jplm/source/Tests/ThirdParty/CppIterToolsTests.cpp:471: Failure
Expected equality of these values:
  expected[i]
    Which is: -0.5
  counted[i]
    Which is: 1.0325971998082053e-321
/home/pedrogf/Projects/LightFields/ReferenceSoftware/REPO/jplm/source/Tests/ThirdParty/CppIterToolsTests.cpp:471: Failure
Expected equality of these values:
  expected[i]
    Which is: -1
  counted[i]
    Which is: 0
`

However, the equivalent Python code works fine:

```python
import itertools
for i in itertools.count(1.0, -0.5):
     print(i)
     if i <= -1:
         break
```
`
1.0
0.5
0.0
-0.5
-1.0
`

**Comment by ryanhaining** [comment]
Definitely strange behavior. I'll have a closer look when I can soon,
thanks.

**Comment by ryanhaining** [comment]
TIL that `numeric_limits::min` returns 0 for floating point types and what I actually need is `numeric_limits::lowest`. Since `count()` can't actually go to infinity, it is implemented as a range that goes to the max or min value for the given type if the step is positive or negative respectively, though it would be UB to actually take this range all the way to the end. Simply replacing `min` with `lowest` in `count.hpp` fixes this.

Thanks again!
